# Generated by Django 4.1.1 on 2022-10-20 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rename_codigo_taller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='propietarioId',
        ),
        migrations.AddField(
            model_name='carro',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
