# Generated by Django 4.1.1 on 2022-11-27 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221108_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carro')),
            ],
        ),
    ]
