# Generated by Django 4.0.4 on 2022-11-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221108_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
