# Generated by Django 4.1.1 on 2022-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
