# Generated by Django 4.1.1 on 2022-11-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recordatorio_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='kilometrajeInicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
